// Жанры для стартового каталога: название книги → жанры (см. lib/genres.ts).
export const SEED_GENRES: Record<string, string[]> = {
  "Война и мир": ["classics", "historical"],
  "Анна Каренина": ["classics", "romance"],
  "Преступление и наказание": ["classics"],
  "Идиот": ["classics"],
  "Бесы": ["classics"],
  "Братья Карамазовы": ["classics", "philosophy"],
  "Евгений Онегин": ["classics", "poetry"],
  "Капитанская дочка": ["classics", "historical"],
  "Герой нашего времени": ["classics"],
  "Мёртвые души": ["classics", "humor"],
  "Отцы и дети": ["classics"],
  "Обломов": ["classics"],
  "Мастер и Маргарита": ["classics", "fantasy"],
  "Собачье сердце": ["classics", "science-fiction", "humor"],
  "Тихий Дон": ["classics", "historical"],
  "Доктор Живаго": ["classics", "historical"],
  "Мы": ["dystopia", "science-fiction"],
  "Двенадцать стульев": ["humor", "adventure"],
  "Золотой телёнок": ["humor", "adventure"],
  "Пикник на обочине": ["science-fiction"],
  "Трудно быть богом": ["science-fiction"],
  "Понедельник начинается в субботу": ["science-fiction", "humor"],
  "Улитка на склоне": ["science-fiction"],
  "Град обреченный": ["science-fiction", "dystopia"],
  "1984": ["dystopia", "classics"],
  "Скотный двор": ["dystopia", "classics"],
  "О дивный новый мир": ["dystopia", "science-fiction"],
  "451 градус по Фаренгейту": ["dystopia", "science-fiction"],
  "Марсианские хроники": ["science-fiction"],
  "Над пропастью во ржи": ["classics", "young-adult"],
  "Убить пересмешника": ["classics"],
  "Великий Гэтсби": ["classics", "romance"],
  "Три товарища": ["classics", "romance"],
  "Маленький принц": ["classics", "children", "philosophy"],
  "Гордость и предубеждение": ["classics", "romance"],
  "Джейн Эйр": ["classics", "romance"],
  "Франкенштейн": ["classics", "horror", "science-fiction"],
  "Дракула": ["classics", "horror"],
  "Граф Монте-Кристо": ["classics", "adventure"],
  "Три мушкетёра": ["classics", "adventure", "historical"],
  "Моби Дик": ["classics", "adventure"],
  "Приключения Тома Сойера": ["classics", "adventure", "children"],
  "Имя розы": ["detective", "historical"],
  "Парфюмер": ["thriller"],
  "Повелитель мух": ["classics", "dystopia"],
  "Заводной апельсин": ["dystopia"],
  "Рассказ служанки": ["dystopia"],
  "Хоббит, или Туда и обратно": ["fantasy", "adventure", "children"],
  "Властелин колец": ["fantasy", "adventure"],
  "Гарри Поттер и философский камень": ["fantasy", "children", "young-adult"],
  "Игра престолов": ["fantasy"],
  "Дюна": ["science-fiction"],
  "Основание": ["science-fiction"],
  "Я, робот": ["science-fiction"],
  "Солярис": ["science-fiction", "philosophy"],
  "Мечтают ли андроиды об электроовцах?": ["science-fiction"],
  "Нейромант": ["science-fiction"],
  "Игра Эндера": ["science-fiction", "young-adult"],
  "Автостопом по галактике": ["science-fiction", "humor"],
  "Марсианин": ["science-fiction", "adventure"],
  "Задача трёх тел": ["science-fiction"],
  "Ложная слепота": ["science-fiction"],
  "Сияние": ["horror"],
  "Оно": ["horror"],
  "Зелёная миля": ["fantasy"],
  "Убийство в «Восточном экспрессе»": ["detective"],
  "Десять негритят": ["detective"],
  "Собака Баскервилей": ["detective", "classics"],
  "Код да Винчи": ["thriller", "detective"],
  "Девушка с татуировкой дракона": ["thriller", "detective"],
  "Книжный вор": ["historical", "young-adult"],
  "Sapiens. Краткая история человечества": ["history", "science"],
  "Думай медленно… решай быстро": ["psychology", "science"],
  "Краткая история времени": ["science"],
  "Эгоистичный ген": ["science"],
  "Ружья, микробы и сталь": ["history", "science"],
  "Человек в поисках смысла": ["psychology", "biography", "philosophy"],
  "Атомные привычки": ["self-help", "psychology"],
  "Чёрный лебедь": ["business", "philosophy"],
  "Стив Джобс": ["biography", "business"],
};
